spring.application.name=LoginRegistrationSpringMvc
spring.datasource.url=jdbc:mysql://localhost:3306/DataJpaRepository12pm
spring.datasource.username=root
spring.datasource.password=Ramjan123
server.port=9090
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp








# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true