spring.application.name=04SpringBootCoreMultipleTypePropertiesEx
com.app.id = 102
com.app.code = 345HT
com.app.orders = Ramjan,Rohit,Aman
com.app.list= 3,4,5,6
com.app.map.Order1 = Ramjan
com.app.map.Order2 = Rohit
com.app.P.pId = 23
com.app.P.Pcode = 2345
