spring.application.name=DataJpaMapping
# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/ManyToOne

# Database username
spring.datasource.username=root

# Database password
spring.datasource.password=Ramjan123

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=create

# Show SQL queries in console
spring.jpa.show-sql=true

